In [2]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (2.0.2)

Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
arr = np.reshape(arr,(2,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr = arr[5:15]
print(arr)

[ 6  7  8  9 10 11 12 13 14 15]

In [8]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [16]:
# prompt: create a dataframe with 2 columns and 10 rows

import pandas as pd
data = {'apples' : 3, 'bananas': 2,'oranges': 1}
data = pd.Series(data)
data['pears'] = 4
print(data)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [30]:
import pandas as pd
data = {'name' : ['john','abin','gokul','aksan','joel','justin','tinu','midhun','nibu','aswin'],
        'age' : [20,21,22,23,24,35,26,30,28,29],
        'gender' : ['male','male','male','male','male','male','male','male','male','male']}
data = pd.DataFrame(data)
print(data)

     name  age gender
0    john   20   male
1    abin   21   male
2   gokul   22   male
3   aksan   23   male
4    joel   24   male
5  justin   35   male
6    tinu   26   male
7  midhun   30   male
8    nibu   28   male
9   aswin   29   male

Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [31]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
data['occupation'] = occupations
print(data)

     name  age gender  occupation
0    john   20   male  Programmer
1    abin   21   male     Manager
2   gokul   22   male     Analyst
3   aksan   23   male  Programmer
4    joel   24   male     Manager
5  justin   35   male     Analyst
6    tinu   26   male  Programmer
7  midhun   30   male     Manager
8    nibu   28   male     Analyst
9   aswin   29   male  Programmer

Select the rows of the dataframe where the age is greater than or equal to 30.

In [32]:
newdata = data[data['age'] >= 30]
newdata

     name  age gender occupation
5  justin   35   male    Analyst
7  midhun   30   male    Manager

Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [33]:
data.to_csv('output.csv', index=False)
read_data = pd.read_csv('output.csv')
read_data

     name  age gender  occupation
0    john   20   male  Programmer
1    abin   21   male     Manager
2   gokul   22   male     Analyst
3   aksan   23   male  Programmer
4    joel   24   male     Manager
5  justin   35   male     Analyst
6    tinu   26   male  Programmer
7  midhun   30   male     Manager
8    nibu   28   male     Analyst
9   aswin   29   male  Programmer